name=MULTI
version=0.0.1
author=Chung
maintainer=Chung <cne.tech.sp@gmail.com>
sentence=Base multi library for BK26-002 project
paragraph=Support multiple boards and modules
category=Other
url=https://github.com/cnetechsp/MULTI
architectures=*